theme: minima
title: IBM Cloud Basics
description: Dieser Workshop beinh√§lt die Konzepte Identity and Access Management (IAM) / Zugriffsberechtigungen (Cloud Owner vs. Admin, feingranulares Rollenkonzep), Staging / Isolation von Projekten & Ressourcen (Ressourcengruppen, Enterprise Account Konzept), Usage (Wer hat welchen Service gebucht, wird er noch genutzt), Notification (professioneller Betrieb) & Ticketing ,Observability (Logging, Monitoring, Auditing)
email: felix.janakow@ibm.com
author: Felix Janakow

# Minima Theme Konfiguration
minima:
  skin: auto  # Optionen: auto, classic, dark, solarized, solarized-dark
  social_links:
    - { platform: github, user_url: "https://github.com/felix-janakow" }
    - { platform: email, user_url: "mailto:felix.janakow@ibm.com" }

# Weitere wichtige Einstellungen
show_excerpts: false